FROM ubuntu:22.04
RUN apt-get update && apt-get install -y \
    gdb cmake

RUN apt-get install -y \
    libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev \
    libjsoncpp-dev